import React from "react";
import { Navbar, Footer } from "./index";

const Hardware = () => {
  return (
    <div className="w-full min-h-screen">
      <Navbar />

      {/*Section - 1 */}
      <div className="flex-grow flex flex-col items-start justify-center py-40 px-32">
        <h1 className="text-4xl font-extrabold text-gray-800 mb-6 italic">
          Renewable Energy Monitoring System
        </h1>

        <h2 className="text-2xl font-bold text-gray-700 mb-4">
          Hardware Components
        </h2>

        {/* Hardware Section */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 cursor-pointer">
          {/* Solar Panel System */}
          <div className="p-4 border rounded-lg bg-gray-100 hover:bg-gray-200 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Solar Panel System</h2>
            <p className="text-gray-600">
              Comprehensive solar panel setup with advanced sensors measuring
              solar irradiance, panel temperature, battery voltage, and current.
            </p>
          </div>

          {/* IoT Devices and Communication */}
          <div className="p-4 border rounded-lg bg-gray-100 hover:bg-gray-200 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">
              IoT Devices and Communication
            </h2>
            <p className="text-gray-600">
              Integrated IoT devices and a communication gateway ensuring secure
              data transmission between sensors and the cloud server.
            </p>
          </div>

          {/* Sensors */}
          <div className="p-4 border rounded-lg bg-gray-100 hover:bg-gray-200 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Sensors</h2>
            <p className="text-gray-600">
              Specialized sensors for monitoring solar irradiance, panel
              temperature, battery voltage, and current, providing accurate data
              for analysis.
            </p>
          </div>
        </div>
      </div>

      {/* section 2 */}
      <div className="flex-grow flex flex-col items-start justify-center py-16 px-32 bg-black text-white">
        <h2 className="text-2xl font-bold text- mb-4">Solar Pannel System</h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 cursor-pointer">
          {/* Solar Panels */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-900 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Solar Panels</h2>
            <p className="text-gray-300">
              High-efficiency solar panels capture sunlight and convert it into
              direct current (DC) power to initiate the solar energy generation
              process.
            </p>
          </div>

          {/* Inverter */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Inverter</h2>
            <p className="text-gray-300">
              Converts the DC power generated by solar panels into alternating
              current (AC) for household use, making it compatible with standard
              electrical systems.
            </p>
          </div>

          {/* Battery Storage */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Battery Storage</h2>
            <p className="text-gray-300">
              Stores surplus energy produced during peak sunlight hours,
              ensuring a continuous power supply during periods of low or no
              sunlight.
            </p>
          </div>

          {/* Charge Controller */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Charge Controller</h2>
            <p className="text-gray-300">
              Regulates and optimizes the voltage and current flowing between
              the solar panels and the batteries, preventing overcharging or
              undercharging and ensuring the longevity of the battery system.
            </p>
          </div>

          {/* Sensors */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Sensors</h2>
            <p className="text-gray-300">
              Various sensors, including those for temperature, sunlight
              intensity, and panel orientation, contribute to monitoring and
              optimizing the performance of the solar panel system for enhanced
              efficiency and data-driven decision-making.
            </p>
          </div>
        </div>
      </div>
      {/* Section - 3 */}
      <div className="flex-grow flex flex-col items-start justify-center py-16 px-32 bg-white text-black">
        <h2 className="text-2xl font-bold mb-4">
          IoT Devices and Communication
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 cursor-pointer">
          {/* Microcontroller/Processor*/}
          <div className="p-4 border rounded-lg bg-white hover:bg-gray-100 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">
              Microcontroller/Processor
            </h2>
            <p className="text-gray-700">
              Utilizing Arduino or Raspberry Pi enables efficient data
              processing and control within our solar panel system, ensuring
              seamless integration with various sensors and components.
            </p>
          </div>

          {/* Cellular Module */}
          <div className="p-4 border rounded-lg bg-white hover:bg-gray-100 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Cellular Module</h2>
            <p className="text-gray-700">
              The inclusion of a Cellular Module facilitates remote data
              transmission and control, allowing real-time monitoring and
              management of the solar power system, even in distant locations.
            </p>
          </div>

          {/* Wi-Fi Module */}
          <div className="p-4 border rounded-lg bg-white hover:bg-gray-100 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Wi-Fi Module</h2>
            <p className="text-gray-700">
              With a Wi-Fi Module, our solar panel system can communicate
              locally, enabling data exchange within the network. This ensures
              quick and reliable information flow for efficient monitoring and
              control.
            </p>
          </div>

          {/* GPS Module */}
          <div className="p-4 border rounded-lg bg-white hover:bg-gray-100 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">GPS Module</h2>
            <p className="text-gray-700">
              Incorporating a GPS Module provides geolocation capabilities,
              enhancing our project's functionality by enabling precise tracking
              of the solar panel system's location. This feature contributes to
              better system management and optimization based on geographical
              data.
            </p>
          </div>

          {/* Bluetooth Module */}
          <div className="p-4 border rounded-lg bg-white hover:bg-gray-100 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Bluetooth Module</h2>
            <p className="text-gray-700">
              The addition of a Bluetooth Module allows for short-range
              communication with nearby devices, fostering connectivity within
              the system. This feature enhances local interactions and
              coordination among different components for improved system
              efficiency.
            </p>
          </div>
        </div>
      </div>
      {/* Section - 4 */}
      <div className="flex-grow flex flex-col items-start justify-center py-16 px-32 bg-black text-white">
        <h2 className="text-2xl font-bold text- mb-4">Sensors</h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 cursor-pointer">
          {/* Current Sensor */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-900 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Current Sensor</h2>
            <p className="text-gray-300">
              Integrating a Current Sensor allows precise measurement of current
              flow within our solar panel system, providing critical data for
              optimizing energy production and consumption.
            </p>
          </div>

          {/* Voltage Sensor */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Voltage Sensor</h2>
            <p className="text-gray-300">
              The Voltage Sensor plays a crucial role in monitoring voltage
              levels across various components, aiding in the assessment of
              system health and ensuring optimal performance of our solar power
              infrastructure.
            </p>
          </div>

          {/* Temperature Sensor */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Temperature Sensor</h2>
            <p className="text-gray-300">
              Employing Temperature Sensors enables real-time monitoring of
              solar panel and battery temperatures. This data is instrumental in
              preventing overheating, enhancing overall system safety, and
              optimizing energy output based on environmental conditions.
            </p>
          </div>

          {/* Light Intensity Sensor */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Light Intensity Sensor</h2>
            <p className="text-gray-300">
              The Light Intensity Sensor serves as a key element in predicting
              and optimizing power generation. By accurately measuring sunlight
              intensity, our system can dynamically adjust to varying light
              conditions, maximizing energy harvesting efficiency.
            </p>
          </div>

          {/* Humidity Sensor */}
          <div className="p-4 border rounded-lg bg-black hover:bg-gray-800 shadow-md transition duration-300">
            <h2 className="text-xl font-bold mb-2">Humidity Sensor</h2>
            <p className="text-gray-300">
              The Humidity Sensor contributes to a comprehensive environmental
              monitoring approach. By tracking humidity levels, our solar panel
              system gains insights into the surrounding conditions, ensuring
              resilience against adverse weather and environmental factors for
              sustained performance.
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Hardware;
